import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import type { LatchPolicy } from "./types.js";

export interface RenderActionTypesOptions {
  /** Policy path shown in the generated header, e.g. `latch.yaml`. */
  file?: string;
}

/**
 * The action-name type a policy declares, as TypeScript source:
 * `stripe.refunds.create` becomes a literal, `stripe.*` becomes
 * `` `stripe.${string}` & {} ``, and an allowed bare `*` widens to `string`.
 *
 * Wildcard deny rules are left out — they guard actions rather than name
 * them, and the global form a bare `filesystem.paths` entry normalizes to
 * (`*`) would otherwise widen every gate to `string`. Under `default: allow`
 * any name is callable, so the union stays open to arbitrary strings.
 */
export function actionType(policy: LatchPolicy): string {
  return actionMembers(policy).join(" | ");
}

function actionMembers(policy: LatchPolicy): string[] {
  const members = new Set<string>();
  for (const rule of policy.allow) members.add(patternType(rule.action));
  for (const rule of policy.deny) {
    if (!rule.action.endsWith("*")) members.add(patternType(rule.action));
  }
  if (members.has("string")) return ["string"];
  if (policy.default === "allow") members.add("(string & {})");
  return members.size === 0 ? ["never"] : [...members];
}

/**
 * Render a declaration file that registers the policy's action names with
 * latch, so `createGate` narrows check/assert/wrap without a type argument.
 */
export function renderActionTypes(
  policy: LatchPolicy,
  options: RenderActionTypesOptions = {},
): string {
  const source = options.file ?? "latch.yaml";
  const members = actionMembers(policy);
  const body =
    members.length === 1
      ? ` ${members[0]};`
      : `\n${members.map((member) => `      | ${member}`).join("\n")};`;
  return `// Generated by \`latch types\` from ${source}. Do not edit; rerun after changing the policy.
export {};

declare module "@vyr-e/latch" {
  interface Register {
    action:${body}
  }
}
`;
}

/** Where the declaration file lives by default: `latch-env.d.ts` beside the policy. */
export function actionTypesPath(policyFile: string): string {
  return join(dirname(policyFile), "latch-env.d.ts");
}

/**
 * Bring the declaration file for a policy up to date. `upToDate` reports the
 * state before any write; with `check`, nothing is written.
 */
export function writeActionTypes(
  policy: LatchPolicy,
  policyFile: string,
  options: { out?: string; check?: boolean } = {},
): { file: string; upToDate: boolean } {
  const file = options.out ?? actionTypesPath(policyFile);
  // Relative to the output, so the content doesn't depend on cwd.
  const source = renderActionTypes(policy, { file: relative(dirname(file), policyFile) });
  const upToDate = existsSync(file) && readFileSync(file, "utf8") === source;
  if (!upToDate && !options.check) writeFileSync(file, source);
  return { file, upToDate };
}

function patternType(pattern: string): string {
  if (pattern === "*") return "string";
  // `& {}` stops TypeScript from absorbing the namespace's literal names into
  // the template, which would drop them from autocomplete.
  if (pattern.endsWith(".*"))
    return `(\`${escapeTemplate(pattern.slice(0, -2))}.\${string}\` & {})`;
  return JSON.stringify(pattern);
}

function escapeTemplate(text: string): string {
  return text.replace(/[\\`$]/g, (char) => `\\${char}`);
}
